//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa
//awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa,awa